Add API tutorial for auto-system-cleanup
enclave-networks/docs pull request #108
Opened 2023-09-26 11:12 UTC by enclave-alistair

Fixes #105

2023-10-02 10:45 UTC, enclave-charlie requested changes

2023-10-02 10:45 UTC, enclave-charlie commented on docs/tutorials/index.md
> +    An example script to clean-up Enclave systems that haven't connected for a while.
Can we make this one line? I think it changes the formatting of every tile on the row otherwise:

![image](https://github.com/enclave-networks/docs/assets/112474401/26fb61ab-ee5e-4454-9d55-95c63d26e69a)

2023-10-02 10:45 UTC, enclave-charlie commented on docs/tutorials/auto-removing-old-systems.md
> +title: "Enclave API Examples: Cleaning up inactive systems"
Should "Examples" be singular here?

2023-10-02 10:45 UTC, enclave-charlie commented on docs/tutorials/auto-removing-old-systems.md
> +One such example is removing systems automatically based on some condition. For example, removing any systems that have not connected to the Enclave Platform for a period of time.
"One such example..." followed by "For example..." is a tad confusing. We also haven't really introduced the purpose of the document here. Maybe something like:

"You can use our [public APIs](../api/index.md) to automate any task achievable manually in the Enclave Portal. 

As an example, we'll demonstrate how to automatically remove any systems that have not connected to the Enclave Platform for a period of time."

2023-10-02 10:45 UTC, enclave-charlie commented on docs/tutorials/auto-removing-old-systems.md
> +We've got a working PowerShell script below (it's easy to invoke our APIs with PowerShell and the `Invoke-RestMethod` cmdlet), but what we'll do is:
I don't think this sentence successfully introduces the purpose of this section (to summarise the steps we'll have to take to clean up inactive systems). It also only partially introduces the script (what does the script do?).

2023-10-02 10:45 UTC, enclave-charlie commented on docs/tutorials/auto-removing-old-systems.md
> +- `-orgId` ; The organisation to run queries against.
I think the semi-colon should be a comma. Seems to be more consistent with how you might introduce something/someone:

"This is Charlie, the CTO in waiting".

2023-10-02 10:45 UTC, enclave-charlie commented on docs/tutorials/auto-removing-old-systems.md
> +- `-test` ; prints out the systems that the script *would* have revoked, but doesn't actually change anything.
"which prints out"

2023-10-05 11:50 UTC, enclave-charlie requested changes

2023-10-05 11:50 UTC, enclave-charlie commented on docs/tutorials/index.md
> +- title: "Enclave API Example: Cleaning up inactive systems"
Should "Cleaning up inactive systems" be "Cleaning Up Inactive Systems"? Feels like the title should be all capitalised.

(Also, the title's still spread over two lines which adds padding to the other tiles on the row. Looks better than it before, though, so I'm less fussed about whether or not this needs fixing)

![image](https://github.com/enclave-networks/docs/assets/112474401/ec1c377b-9fd4-4b10-9fb9-9028d50f2b41)

2023-10-05 11:55 UTC, enclave-alistair commented on docs/tutorials/index.md
> +- title: "Enclave API Example: Cleaning up inactive systems"
Might just have to lump the line-height, I don't want to have to stick to a single line for the title for all tutorial posts.

2023-10-05 11:57 UTC, enclave-charlie approved these changes
Looks great 🚢

2023-10-05 11:57 UTC, enclave-charlie commented on docs/tutorials/index.md
> +- title: "Enclave API Example: Cleaning up inactive systems"
👍

2023-10-05 11:58 UTC, merged