Add documentation on our various OIDC providers
enclave-networks/docs pull request #130
Opened 2023-11-02 17:36 UTC by enclave-alistair

2023-11-08 15:00 UTC, enclave-charlie requested changes

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-custom-oidc.md
> +- The **Authority URL**; this is the root URL of the Identity Provider, sometimes also called the Issuer. It is **not** the metadata URI of the identity provider. The URL should **not** contain a ".w
Full stop rather than a comma between "path value" and "if it does", and a comma after "if it does":

The URL should **not** contain a ".well-known" path value. If it does, it means you've got the wrong value.

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-custom-oidc.md
> +- Optionally, provide an **Audience**. Depending on the identity provider, you may want/need to specify an audience value for the **Relying Party** (which is Enclave). If you do not provide a value,
Don't think we need to replicate "provide" here (given that the verb is introduced above the bullet-points). I'd just go with:

"Optionally, an Audience."

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-duo-sso.md
> +To connect your Duo instance to Enclave, you must first create an Application within Duo. Go to your admin dashboard in Duo and navigate to the **Applications** page, then click **Protect an Applicat
Should "Application" be bold?

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-microsoft-azure.md
> +- Apply [Conditional Access](https://learn.microsoft.com/en-us/entra/identity/conditional-access/overview) to user logins
First two bullet-points are missing full-stops

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-microsoft-azure.md
> +Using security groups you can create finely-grained connectivity rules that map your user security assignments to the resources they can access.
I'd add a comma after "Using security groups"

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-microsoft-azure.md
> +An Azure AD user may be granted time-bound system access through Azure Conditional Access or Privileged Identity Management (PIM) policies to block access from less trusted locations, force users to
Remove "time-bound"? Not sure how it relates to blocking access to less-trusted locations, or enforcing device security compliance posture.

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-microsoft-azure.md
> +The default access token lifetime is between 60-90 minutes, but if needed conditional policy can be applied to the Enclave app integration in the Azure tenant to reduce that time to a smaller number.
"to reduce that time to a smaller number" feels a bit clunky.

 "to reduce the token lifespan"?

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-microsoft-azure.md
> +    In the future we will receive streamed notifications from Azure AD when user memberships change and react dynamically to those events, but that Azure AD feature has not been released as of Novemb
I'd add a comma after "In the future".

The sentence is a bit ambiguous. Are we waiting for an Azure AD feature to be released?

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-okta.md
> +To get started, you need to set up a few things in your Okta tenant. Log in to your Okta tenant with an administrator account, then visit the "Applications" page from the left menu.
"in the menu on the left"?

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-okta.md
> +Press Save when ready to create your Application.
Should "Save" be in bold?

2023-11-08 15:00 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication-okta.md
> +Next, we need to add an Okta **Authorization Server**, to give us an Authority URI and let us customise the tokens sent to Enclave.
Should "Authority URI" be in bold?

2023-11-13 12:40 UTC, enclave-alistair commented on docs/management/trust-requirements/user-authentication-microsoft-azure.md
> +    In the future we will receive streamed notifications from Azure AD when user memberships change and react dynamically to those events, but that Azure AD feature has not been released as of Novemb
I'm just going to take this block out, I'm not sure what it adds tbh.

2023-11-13 14:16 UTC, enclave-charlie approved these changes

2023-11-14 15:40 UTC, merged