Add Azure Files tutorial
enclave-networks/docs pull request #139
Opened 2023-11-22 16:53 UTC by enclave-alistair

Closes #126

2023-11-23 11:10 UTC, enclave-charlie requested changes

2023-11-23 11:10 UTC, enclave-charlie commented on docs/tutorials/secure-private-access-to-azure-files.md
> +    The only significant deviation of these steps from the default instructions is to set a **Static IP** for the private endpoint for you to reference later.
I'd re-link the Azure documentation in "default instructions", or specify "The only significant deviation of these steps from the documentation provided by Azure". Doesn't feel clear enough to me what the "default instructions" are.

2023-11-23 11:10 UTC, enclave-charlie commented on docs/tutorials/secure-private-access-to-azure-files.md
> +     Select **Statically allocate IP address** and choose an IP address for the private endpoint. Following the diagram above, we are allocating **10.1.0.100**, within our 10.1.0.0/24 subnet.
"Following the diagram above, allocate **10.1.0.100**, within our 10.1.0.0/24 subnet." feels a bit unclear to me.

"For the purposes of this tutorial, we've allocated **10.1.0.100**, within our 10.1.0.0/24 subnet."? 
"As per the diagram above, we've allocated **10.1.0.100**, within our 10.1.0.0/24 subnet."?

2023-11-23 11:10 UTC, enclave-charlie commented on docs/tutorials/secure-private-access-to-azure-files.md
> +2. Configure a subnet filter on the policy to only allow access to your private endpoint (**10.1.0.100**) within your **10.1.0.0/24** subnet:
Should **10.1.0.0/24** be in brackets too?

2023-11-23 11:10 UTC, enclave-charlie commented on docs/tutorials/secure-private-access-to-azure-files.md
> +Finally, you can remove public access to your storage account, preventing any access to your file shares from the internet, ensuring that all access is mediated by Enclave.
"and ensuring" flows a bit better to my ear:

"Finally, you can remove public access to your storage account, preventing any access to your file shares from the internet and ensuring that all access is mediated by Enclave."

2023-11-23 11:44 UTC, enclave-alistair commented on docs/tutorials/secure-private-access-to-azure-files.md
> +2. Configure a subnet filter on the policy to only allow access to your private endpoint (**10.1.0.100**) within your **10.1.0.0/24** subnet:
Replaced the brackets with a comma block? Brackets were kind of a callback I guess, but the subnet shouldn't have them.

2023-11-23 13:57 UTC, enclave-charlie commented on docs/tutorials/secure-private-access-to-azure-files.md
> +2. Configure a subnet filter on the policy to only allow access to your private endpoint (**10.1.0.100**) within your **10.1.0.0/24** subnet:
Why shouldn't the subnet have them? I thought it was also an example chosen for the tutorial?

2023-11-24 11:46 UTC, enclave-charlie approved these changes

2023-11-24 11:50 UTC, merged