Added changes to linux docs to show new process
enclave-networks/docs pull request #18
Opened 2022-02-10 14:08 UTC by enclave-tom

2022-02-10 15:09 UTC, enclave-marc-barry requested changes

2022-02-10 15:09 UTC, enclave-marc-barry commented on docs/getting-started/installation.md
> +      === "Ubuntu / Debian"
Hey Tom, this isn't quite right. The indentation is one too many one the whole file. Suggest running in the root of this repo, i'll boot up a local docker container that you can browse to at http://localhost:8000/getting-started/installation/ to preview the changes

```
PS C:\git\enclave\docs> .\run.ps1
```

2022-02-10 15:39 UTC, enclave-tom commented on docs/getting-started/installation.md
> +      === "Ubuntu / Debian"
I've fixed the indentation but i may have found a bug in the code 
![image](https://user-images.githubusercontent.com/94108925/153442031-cb455337-9210-43a0-ae72-8fea0d21dd72.png)

![image](https://user-images.githubusercontent.com/94108925/153442073-7c704427-702a-47c9-b608-3862d4e69567.png)
i now can't get back to the ubuntu instructions

2022-02-10 19:06 UTC, enclave-marc-barry commented
I just pushed a tab fix on `installation.md`, can apply the same fix to linux.md tomorrow if you don't beat me to it

2022-02-10 22:26 UTC, enclave-tom commented
> I just pushed a tab fix on `installation.md`, can apply the same fix to linux.md tomorrow if you don't beat me to it

My only suggestion would be to remove "amazon linux" as that also uses the same commands as in "other"

2022-02-13 18:35 UTC, enclave-marc-barry submitted a review, later dismissed
Seems the tabs aren't a a future proof UI construct, so we'll no doubt need to re-visit again but this looks much better now, thanks Tom.

2022-02-16 11:04 UTC, enclave-alistair requested changes
One indentation issue, and we're missing the linux uninstall instructions for the new distros on /setup/linux.md.

2022-02-16 11:04 UTC, enclave-alistair commented on docs/getting-started/installation.md
> +                <small>Requires at least Fedora 32.</small>
Incorrect indentation here is causing all this to be a code block.

![image](https://user-images.githubusercontent.com/67738909/154251323-179fcc8d-47d3-4c88-b35c-837e5a4aa55e.png)

2022-02-16 17:52 UTC, merged