Add documentation for trust requirements.
enclave-networks/docs pull request #26
Opened 2022-09-26 16:38 UTC by enclave-alistair

2022-09-26 16:39 UTC, enclave-alistair commented
@enclave-charlie, you want to take this as your first docs review?

2022-09-27 09:40 UTC, enclave-charlie requested changes
Some small fixes and a few suggestions, but otherwise looks good.

2022-09-27 09:40 UTC, enclave-charlie commented on docs/management/trust-requirements/index.md
> +    > Want to apply a trust requirement to the receiver side of a policy? Apply the requirement to the tag(s) on the receiver side instead of in the policy.
"instead of to the policy"?

2022-09-27 09:40 UTC, enclave-charlie commented on docs/management/trust-requirements/public-ip-address.md
> +Under IP Ranges, you can specify multiple IP Range rules, with each one being specified as:
Would be nice to get rid of the repetition of the word "specify". Maybe something like: 

"Under IP Ranges, you can specify multiple IP Range rules, using: "

2022-09-27 09:40 UTC, enclave-charlie commented on docs/management/trust-requirements/public-ip-address.md
> +- A single IP,
"A single IP Address"?

2022-09-27 09:40 UTC, enclave-charlie commented on docs/management/trust-requirements/public-ip-address.md
> +- A range of IP Addresses or
The bullet-point list as-a-sentence threw me a bit. Could this be restructured into a more traditional bullet-point list?

2022-09-27 09:40 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication.md
> +A User Authentication trust requirement allows you to require that a user must have authenticated with a nominated **authority** on their device before connectivity can establish.
"can be established" would sound better to my ear.

2022-09-27 09:40 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication.md
> +In addition to generally require authentication via your tenant, you can also specify an Azure AD **Security Group ID**. Users must then be a member of that security group in order to meet the trust
"require" should be "requiring":

"In addition to generally requiring authentication"

2022-09-27 09:40 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication.md
> +Using security groups you can create finely-grained connectivity rules that maps your user security assignments to the resources they can access.
"maps" should be "map"

2022-09-27 09:40 UTC, enclave-charlie commented on docs/management/trust-requirements/user-authentication.md
> +![Getting a Security Group ID from Azure](images/user-authentication-azure-security-group-id.png)
Quite a large blank space under this image

2022-09-27 13:37 UTC, enclave-alistair commented on docs/management/tags.md
> +This makes it easier to manage trust requirements that apply to *all* connectivity for a particular system or group of systems.
I kind of want to refer more generally to connectivity, which can include the absence of connections.

2022-09-27 13:44 UTC, enclave-alistair commented on docs/management/tags.md
> +This makes it easier to manage trust requirements that apply to *all* connectivity for a particular system or group of systems.
If you have an alternative term that still addresses the same thing, open to ideas.

2022-09-27 13:44 UTC, enclave-alistair commented
Absolutely superb review, thanks! Only one disagreement, over the use of the word connections vs connectivity.

2022-09-27 13:51 UTC, enclave-charlie commented on docs/management/tags.md
> +This makes it easier to manage trust requirements that apply to *all* connectivity for a particular system or group of systems.
No need; I've googled the definition and I think you were correct to use it. Just wasn't a word I was familiar with :)

2022-09-27 13:52 UTC, enclave-alistair commented
Changes pushed, ready for re-approve when you're ready.

2022-09-27 14:19 UTC, enclave-charlie approved these changes
LGTM

2022-09-27 14:19 UTC, merged