Add IPFIX documentation
enclave-networks/docs pull request #27
Opened 2022-09-28 00:26 UTC by bcronje

@enclave-alistair I hope this is in line with what you were expecting.

We should maybe consider implementing https://github.com/enclave-networks/fabric/issues/549

2022-09-28 08:23 UTC, enclave-alistair commented on mkdocs.yml
> +      - IPFIX: management/ipfix.md
Suggest we make this title less protocol-specific, perhaps "Network Metadata (IPFIX)"?

Open to alternatives, just feels like the menu item should be less protocol-focussed.

2022-09-28 08:39 UTC, enclave-alistair requested changes
Thanks Beyers, this looks about right. Requested a few additions/amendments, but generally this is at the right level.

2022-09-28 08:39 UTC, enclave-alistair commented on docs/management/ipfix.md
> +Enclave implements an Internet Protocol Flow Information Export (IPFIX) exporter. IPFIX is an IETF protocol that provides a universal standard for the export and collection of IP flow information. Th
Would be handy to have a paragraph here indicating *why* we support IPFIX, i.e. words around network visibility and diagnostics.

2022-09-28 08:39 UTC, enclave-alistair commented on docs/management/ipfix.md
> +IPFIX is configured using the JSON property `FlowMetadata`. Under `FlowMetadata` we provide the following configuration properties and options:
Do you think we should just generally call this feature "Flow Metadata" since that's how we refer to generally? Is that a good 'public' name?

2022-09-28 08:39 UTC, enclave-alistair commented on docs/management/ipfix.md
> +On Linux the Enclave configuration file is located at `/etc/enclave/profiles/Universe.profile` and can be edit using your preferred editor, e.g.
```suggestion
On Linux the Enclave configuration file is located at `/etc/enclave/profiles/Universe.profile` and can be edited using your preferred editor, e.g.
```

2022-09-28 08:39 UTC, enclave-alistair commented on docs/management/ipfix.md
> +- `IpFixCollectors` - A list of zero of more IPFIX collector information in the string format "_Udp/Collector IP Address:Port_" e.g. `Udp/172.16.1.100:4739`. The example specifies that `UDP` is the t
A list of zero more IPFIX collector 'endpoints' perhaps? Information feels like the wrong word/tense here.

2022-09-28 08:39 UTC, enclave-alistair commented on docs/management/ipfix.md
> +IPFIX supports single direction flow information per data record. This means a normal bidirectional flow e.g. a TCP session, will generate two IPFIX data records, one for ingress information and a se
Can we break this bullet point up into multiple paragraphs? Feels a bit like a wall of text.

2022-09-28 08:39 UTC, enclave-alistair commented on docs/management/ipfix.md
> +IPFIX supports single direction flow information per data record. This means a normal bidirectional flow e.g. a TCP session, will generate two IPFIX data records, one for ingress information and a se
`In certain circumstances this might not be ideal, imagine`; use semicolon instead of comma -> `In certain circumstances this might not be ideal;`

2022-09-28 08:39 UTC, enclave-alistair commented on docs/management/ipfix.md
> +> There is one exception to the direction setting. Frames dropped due to violation of [Access Control Rules](/management/policy/#access-control-rules) will always generate an IPFIX record and be expo
Do we also report frames that flows that fail due a trust requirement that isn't met?

2022-09-28 08:39 UTC, enclave-alistair commented on docs/management/ipfix.md
> +- `Interval` - The interval in millisecond that Enclave will generate and export interim IPFIX flow records. If `Interval` is set to 0, then Enclave will not generate interim flow records, but will o
```suggestion
- `Interval` - The interval in milliseconds at which Enclave will generate and export interim IPFIX flow records. If `Interval` is set to 0, then Enclave will not generate interim flow records, but will only generate and export flow records at the end of each flow. Interval should be either 0, or a multiple of 60000 (1 minute) as Enclave only processes interim records on a 1-minute frequency. The default value is 0.
```

2022-09-28 08:39 UTC, enclave-alistair commented on docs/management/ipfix.md
> +To add the IPFIX configuration options, add the JSON settings at the bottom of the Enclave configuration file you edited in Step 2.
```suggestion
To add the IPFIX configuration options, add the JSON settings at the bottom of the Enclave configuration file you opened in Step 2.
```

2022-09-28 08:44 UTC, bcronje commented on mkdocs.yml
> +      - IPFIX: management/ipfix.md
Good idea, I dont even think we need the (IPFIX) in there. Some alternatives:

1. Network Metadata (IPFIX)
2. Network Metadata
3. Network Analytics
4. Flow Analytics
5. Network Analysis
6. Flow Analysis
7. Network Reporting
8. Network Monitoring
9. ?

2022-09-28 08:51 UTC, enclave-alistair commented on mkdocs.yml
> +      - IPFIX: management/ipfix.md
I think there's a few places where we refer to it as "Flow Metadata". Should we call it that? Or "Network Flow Metadata"?

2022-09-28 10:51 UTC, bcronje commented on docs/management/ipfix.md
> +> There is one exception to the direction setting. Frames dropped due to violation of [Access Control Rules](/management/policy/#access-control-rules) will always generate an IPFIX record and be expo
Yes we do, basically if the frame fails evaluation (that includes trust requirement and ACL checks) it will be reported. I will update to include trust requirements.

2022-09-28 11:01 UTC, bcronje commented on mkdocs.yml
> +      - IPFIX: management/ipfix.md
I think that's a good call. I suggest "Network Flow Metadata" as the navigation item, and headers to reinforce it's related to the network, and then in the actual doc it should be acceptable to use "network flow metadata" and just "flow metadata" interchangeably.

2022-09-28 15:46 UTC, enclave-alistair commented on mkdocs.yml
> +      - IPFIX: management/ipfix.md
Sounds good to me.

2022-09-28 22:27 UTC, bcronje commented
@enclave-alistair I rewrote most of the introduction section to address the "why", also added an overview of the typical IPFIX architecture with more detail on collectors etc. Also applied all the other change requests. Note the bit about end-to-end encrypted overlays such as Enclave that makes it hard for traditional network device flow exporters like routers to effectively generate metadata for the underlying application traffic.

2022-09-29 09:42 UTC, enclave-alistair requested changes
Great stuff, one markdown oddity to deal with, then we're good.

2022-09-29 09:42 UTC, enclave-alistair commented on docs/management/network-flow-metadata.md
> +  > There is one exception to the direction setting. Frames dropped due to violation of [Trust Requirements](/management/trust-requirements/) or [Access Control Rules](/management/policy/#access-cont
You actually require one more level of indentation under the bullet point line to make the content render with the correct indentation.

```suggestion
    IPFIX supports single direction flow information per data record. This means a normal bidirectional flow e.g. a TCP session, will generate two IPFIX data records, one for ingress information and a second for egress information. This is the default behaviour and what will be expected when you configure `Both` as the direction.

    In certain circumstances this might not be ideal; imagine you are running Enclave on System A and System B, both have IPFIX enabled and is monitoring a TCP session between them. With the default `Both` direction, System A will export both ingress and egress data, while System B will also export both ingress and egress data. This means you end up with 4 flow records for a single TCP session. With the `SendingToPeer` and `ReceivedFromPeer` direction options you can limit flow information export to either egress information or ingress information respectively.

    > There is one exception to the direction setting. Frames dropped due to violation of [Trust Requirements](/management/trust-requirements/) or [Access Control Rules](/management/policy/#access-control-rules) will always generate an IPFIX record and be exported, irrespective of the direction setting. For example, even if you have configure `ReceivedFromPeer`, if an outgoing frame to a remote Enclave peer is dropped due to either a [Trust Requirements](/management/trust-requirements/) or an [Access Control Rules](/management/policy/#access-control-rules) violation, Enclave will still report on this egress record.
```

2022-09-29 10:14 UTC, bcronje commented
> Great stuff, one markdown oddity to deal with, then we're good.

Done, applied you change.

2022-09-29 10:54 UTC, enclave-alistair approved these changes
🚀

2022-09-29 10:55 UTC, merged