add notes about dns query order
enclave-networks/docs pull request #29
Opened 2022-11-04 13:03 UTC by enclave-marc-barry

2022-11-04 15:39 UTC, enclave-charlie requested changes
One spelling mistake. The rest are just suggestions.

2022-11-04 15:39 UTC, enclave-charlie commented on docs/management/dns.md
> +DNS changes made in the portal are propagated immediately to every impacted system, so unlike traditional DNS resolvers, Enclave records don't specify a time to live value (actually they do, but the
I'd add a full stop before "anything" to break up the paragraph. I also think it's worth changing "encouraged not to catche the response and immediately expire it" to "encouraged to immatediately expire the response rather than cache it", so it doesn't sound like we're discouraging people from expiring the response.  In total:

"DNS changes made in the portal are propagated immediately to every impacted system, so unlike traditional DNS resolvers, Enclave records don't specify a time to live value (actually they do, but the TTL is 0). Anything which queries the Enclave stub resolver is encouraged to immatediately expire the response rather than cache it, including the operating system."

2022-11-04 15:39 UTC, enclave-charlie commented on docs/management/dns.md
> +DNS changes made in the portal are propagated immediately to every impacted system, so unlike traditional DNS resolvers, Enclave records don't specify a time to live value (actually they do, but the
"Therefor" is missing an "e".

2022-11-04 15:39 UTC, enclave-charlie commented on docs/management/dns.md
> +> Note that a System will only gain knowledge of an Enclave DNS entry if there's an active policy connect it and one or more of the target system(s) to which the DNS record resolves.
"if there's an active policy connecting it to one or more of the target system(s) to which the DNS Record resolves."?

2022-11-04 15:39 UTC, enclave-charlie commented on docs/management/dns.md
> +When the operating system attempts to resolve the name `intranet.contoso.com` it will first question the local stub DNS resolver run by the Enclave agent. As this name was configured in the Portal th
Might be nice to have a comma between "As this was name was configured in the Portal" and "the stub resolver will answer the question and the name will be resolved."

2022-11-04 15:39 UTC, enclave-charlie commented on docs/management/dns.md
> +If the operating system, or other software attempts to resolve a hostname that is not configured in the Enclave portal, the local stub resolver will still receive the question, but answer with a `SRV
Is this missing a comma? Should it be:

"If the operating system, or other software, attempts to resolve a hostname..."?

2022-11-04 16:43 UTC, enclave-marc-barry commented on docs/management/dns.md
> +DNS resolution in Enclave happens based on a fan-out approach. When attempting to resolve a DNS hostname, the operating system will first question the Enclave DNS stub resolver, if the stub resolver
magic, thank you

2022-11-04 16:44 UTC, enclave-marc-barry commented on docs/management/dns.md
> +DNS changes made in the portal are propagated immediately to every impacted system, so unlike traditional DNS resolvers, Enclave records don't specify a time to live value (actually they do, but the
Great, agreed. Thank you

2022-11-04 16:49 UTC, enclave-marc-barry commented on docs/management/dns.md
> +> Note that a System will only gain knowledge of an Enclave DNS entry if there's an active policy connect it and one or more of the target system(s) to which the DNS record resolves.
Yeah not so clear, good spot on adding `record` - that helps.

I've also added an example to try and help clarify - "For example consider two systems, a user and a Postgres database server. The user can only resolve `db.enclave` if there's a policy connecting that user to the Postgres database server, and the Enclave DNS record `db.enclave` is set to resolve to the Postgres database server."

2022-11-04 16:50 UTC, enclave-marc-barry commented on docs/management/dns.md
> +> Note that a System will only gain knowledge of an Enclave DNS entry if there's an active policy connect it and one or more of the target system(s) to which the DNS record resolves.
Let me know if you think that works

2022-11-09 09:27 UTC, enclave-charlie commented on docs/management/dns.md
> +> Note that a System will only gain knowledge of an Enclave DNS entry if there's an active policy connect it and one or more of the target system(s) to which the DNS record resolves.
Yep looks good to me :)

2022-11-09 09:28 UTC, enclave-charlie approved these changes
Looks good 👍

2022-11-09 10:14 UTC, merged