Feature/guacamole
enclave-networks/docs pull request #35
Opened 2023-01-24 09:36 UTC by enclave-charlie

2023-01-24 12:00 UTC, enclave-tom requested changes
Really well written just some comments from a technical point of view!

2023-01-24 12:00 UTC, enclave-tom commented on docs/kb/guacamole.md
> +1. To begin with, install Docker. Installation instructions per Linux distro can be found here: [https://docs.docker.com/desktop/install/ubuntu/](https://docs.docker.com/desktop/install/ubuntu/).
May want to link to here instead https://docs.docker.com/engine/install/#server

2023-01-24 12:00 UTC, enclave-tom commented on docs/kb/guacamole.md
> +2. Open the terminal and navigate to a directory of your choice (e.g. `cd home/ec2-user`). Enter `mkdir guacamoleCompose` to create a folder called `guacamoleCompose`.
`cd home/ec2-user` will only work if you're in the linux root directory. If you want to put them in the users home folder. use `cd ~` instead

2023-01-24 12:00 UTC, enclave-tom commented on docs/kb/guacamole.md
> +2. Open the terminal and navigate to a directory of your choice (e.g. `cd home/ec2-user`). Enter `mkdir guacamoleCompose` to create a folder called `guacamoleCompose`.
possibly worth re writing the second part of this line, something along the lines of create a guacamole folder by running `mkidr guacamoleCompose`  etc

2023-01-24 12:00 UTC, enclave-tom commented on docs/kb/guacamole.md
> +3. Copy and paste the following text into a file titled `docker-compose.yml`. Modify both `POSTGRES_PASSWORD` fields using a text editor of your choice and enter an enrolment key into the `ENCLAVE_EN
file called rather than titled.

We should also make mention to `nano` a super easy text editor. 

We should encourage ephemeral keys regardless as these docker containers will be created and deleted fairly frequently for things like updates etc

2023-01-24 12:00 UTC, enclave-tom commented on docs/kb/guacamole.md
> +4. Copy `docker-compose.yml` into the `guacamoleCompose` folder. If your Linux distro was installed without a GUI, it may be easier to download and edit the file on another machine. Tools like WinSCP
why aren't we creating the file in `guacamoleCompose`?

2023-01-24 12:00 UTC, enclave-tom commented on docs/kb/guacamole.md
> +4. Copy `docker-compose.yml` into the `guacamoleCompose` folder. If your Linux distro was installed without a GUI, it may be easier to download and edit the file on another machine. Tools like WinSCP
Most people will be familiar with the linux CLI. we should help them with it rather than encourage the use of a GUI

2023-01-24 12:00 UTC, enclave-tom commented on docs/kb/guacamole.md
> +5. Copy the text below into a file titled `prepare.sh`. This file will initialise the Postgres database for us. As above, copy the file `prepare.sh` into`guacamoleCompose`.
file called. and again we can create the file in guacamole compose. by ensuring we're in the folder with `cd guacamoleCompose` then running `nano prepare.sh`

2023-01-24 12:00 UTC, enclave-tom commented on docs/kb/guacamole.md
> +7. Enter `sudo docker compose up -d` to build and run the docker containers for the service. Enclave and Guacamole should now be running.
rather than enter, Run makes more sense here.

2023-01-24 12:00 UTC, enclave-tom commented on docs/kb/guacamole.md
> +2. In your web browser, navigate to `[YourVirtualNetworkAddress]:8080/guacamole`. You should be redirected to the Guacamole login page. If you've registered a DNS name for the server, you can also us
give an example of the enclave `[systemid].id.enclave` dns name as these are auto assigned!

2023-01-24 12:17 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +4. Copy `docker-compose.yml` into the `guacamoleCompose` folder. If your Linux distro was installed without a GUI, it may be easier to download and edit the file on another machine. Tools like WinSCP
In my case, AWS butchered the formatting when I tried to copy the text directly into the file using nano (deleted all line endings and indentation). I ended up creating it on my local machine and copying it over. Is there a better way?

2023-01-24 12:20 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +3. Copy and paste the following text into a file titled `docker-compose.yml`. Modify both `POSTGRES_PASSWORD` fields using a text editor of your choice and enter an enrolment key into the `ENCLAVE_EN
I wanted to avoid using "called" too often - it starts to become quite repetitive to read otherwise. Agreed "titled" is a bit awkward - how about "named"?

2023-01-24 12:31 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +4. Copy `docker-compose.yml` into the `guacamoleCompose` folder. If your Linux distro was installed without a GUI, it may be easier to download and edit the file on another machine. Tools like WinSCP
Ended up looking like this:

![image](https://user-images.githubusercontent.com/112474401/214292283-23f42b51-4142-4290-9a24-dfe78a846d35.png)

2023-01-24 15:27 UTC, enclave-tom commented on docs/kb/guacamole.md
> +    ```yaml
this is bash not yaml

2023-01-25 10:37 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +2. Open the terminal and navigate to a directory of your choice (e.g. `cd home/ec2-user`). Enter `mkdir guacamoleCompose` to create a folder called `guacamoleCompose`.
It's only an example, really - I'm not suggesting they should put it there

2023-01-25 11:52 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +7. Enter `sudo docker compose up -d` to build and run the docker containers for the service. Enclave and Guacamole should now be running.
Sprinkled in a couple anyway to break it up a bit

2023-01-25 12:23 UTC, enclave-tom requested changes
Looks good just a few small changes, i'm glad the issue with creating files was due to AWS!

2023-01-25 12:23 UTC, enclave-tom commented on docs/kb/guacamole.md
> +1. To begin with, install Docker. Installation instructions per Linux distro can be found here: https://docs.docker.com/engine/install/#server.
`[found here](https://docs.docker.com/engine/install/#server)`

2023-01-25 12:23 UTC, enclave-tom commented on docs/kb/guacamole.md
> +2. Open the terminal and navigate to a directory of your choice (e.g. `cd home/ec2-user`). Enter `mkdir guacamoleCompose` to create a folder called `guacamoleCompose`.
that's fine but let's make the tutorial as clear as possible using `cd ~` will always go to the current users home folder as it's an alias

2023-01-25 12:23 UTC, enclave-tom commented on docs/kb/guacamole.md
> +3. Run `nano docker-compose.yml` to create and open an empty file called `docker-compose.yml` in the nano text editor. Copy and paste into it the text below. Modify both `POSTGRES_PASSWORD` fields an
Since we're using docker we should point them to an `ephemeral` key regardless. As that's what they're designed for.

2023-01-25 12:23 UTC, enclave-tom commented on docs/kb/guacamole.md
> +4. As above, create a file called `prepare.sh` and copy into it the text below. This file will initialise the Postgres database for us.
This may be something that comes up from actual use but may be worth saying create with `nano` but i'm easy either way

2023-01-25 12:23 UTC, enclave-tom commented on docs/kb/guacamole.md
> +2. In your web browser, navigate to `[YourVirtualNetworkAddress]:8080/guacamole`. You should be redirected to the Guacamole login page. If you've registered a DNS name for the server, you can also us
we should link to the DNS docs instead

2023-01-25 12:23 UTC, enclave-tom commented on docs/kb/guacamole.md
> +2. Open the terminal and navigate to a directory of your choice (e.g. run `cd home/ec2-user`). Enter `mkdir guacamoleCompose` to create a folder called `guacamoleCompose`.
we should probably also add `cd guacamoleCompose` as the other steps assume we're in that folder

2023-01-25 12:24 UTC, enclave-tom commented on docs/kb/guacamole.md
> +7. Enter `sudo docker compose up -d` to build and run the docker containers for the service. Enclave and Guacamole should now be running.
i'm happy either way but for me i'd be more inclined to say "Run" as we're running that command rather than just entering it.

2023-01-25 12:40 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +3. Run `nano docker-compose.yml` to create and open an empty file called `docker-compose.yml` in the nano text editor. Copy and paste into it the text below. Modify both `POSTGRES_PASSWORD` fields an
Do docker containers change their IP address? Mine seems to stay the same when I reboot the AWS instance

2023-01-25 12:52 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +3. Run `nano docker-compose.yml` to create and open an empty file called `docker-compose.yml` in the nano text editor. Copy and paste into it the text below. Modify both `POSTGRES_PASSWORD` fields an
My gut feeling is that if I used ~ I'd have to explain what it means, which feels like a detail-too-far. I really just want them to use the `cd` command to change directory to one they're happy with, so I've updated the line to reflect that.

2023-01-26 10:09 UTC, enclave-tom commented on docs/kb/guacamole.md
> +3. Run `nano docker-compose.yml` to create and open an empty file called `docker-compose.yml` in the nano text editor. Copy and paste into it the text below. Modify both `POSTGRES_PASSWORD` fields an
docker containers can be destryoed and created fairly easily. for example if you were to update the enclave image the old container would be removed. so allowing for it to be ephemeral would make the most sense. Also from the point of view of spinning up and spinning down a container.

2023-01-26 10:25 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +2. In your web browser, navigate to `[YourVirtualNetworkAddress]:8080/guacamole`. You should be redirected to the Guacamole login page. If you've registered a DNS name for the server, you can also us
Added it in the note section under step 3

2023-01-26 10:32 UTC, enclave-tom submitted a review, later dismissed
Looks good! waiting on a 2nd review from @enclave-alistair

2023-01-26 13:08 UTC, enclave-alistair requested changes
A few bits.

2023-01-26 13:08 UTC, enclave-alistair commented on docs/kb/guacamole.md
> +This is astep-by-step guide to installing and using Guacamole with Enclave on Linux. For this purpose, we're going to use Docker, which you can read more about at https://www.docker.com/. Once we're
"This is a step-by-step guide"

2023-01-26 13:08 UTC, enclave-alistair commented on docs/kb/guacamole.md
> +3. Run `nano docker-compose.yml` to create and open an empty file called `docker-compose.yml` in the nano text editor. Copy and paste into it the text below. Modify both `POSTGRES_PASSWORD` fields an
```suggestion
3. Run `nano docker-compose.yml` to create and open an empty file called `docker-compose.yml` in the nano text editor. Copy and paste into it the yaml file below. Modify both `POSTGRES_PASSWORD` fields and enter an enrolment key into the `ENCLAVE_ENROLMENT_KEY` field. Whatever password you choose, its important that both fields match. Once you're done, save and exit by typing `ctrl-x` followed by `y`.
```

2023-01-26 13:08 UTC, enclave-alistair commented on docs/kb/guacamole.md
> +> ****Note****  You may prefer to use an ephemeral enrolment key. Systems enrolled using an ephemeral enrolment key are automatically removed from your Enclave organisation when they disconnect. By a
Switch to a 'tip' admonition; also, use relative path references when linking.

```suggestion
!!! tip  

    You may prefer to use an ephemeral enrolment key. Systems enrolled using an ephemeral enrolment key are automatically removed from your Enclave organisation when they disconnect. By adding a tag to the key, you can also automatically assign the Guacamole server the same DNS name on startup. You can read more about DNS [here](../management/dns.md).
```

2023-01-26 13:08 UTC, enclave-alistair commented on docs/kb/guacamole.md
> +7. Navigate to `portal.enclave.io` in your browser and identify the Guacamole server; it should have enrolled using `ENCLAVE_ENROLMENT_KEY`. Make sure the system is approved and connected to your loc
Tell them what policy to create, and what port numbers they need to allow in their ACL.

2023-01-26 13:08 UTC, enclave-alistair commented on docs/kb/guacamole.md
> +2. In your web browser, navigate to `[YourVirtualNetworkAddress]:8080/guacamole`. You should be redirected to the Guacamole login page. If you've registered a DNS name for the server, you can also us
Can we add a setting to the YAML so guacamole uses port 80 instead of 8080?  Not a huge deal if not, but would make for a better URL at the end.

2023-01-26 13:21 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +7. Navigate to `portal.enclave.io` in your browser and identify the Guacamole server; it should have enrolled using `ENCLAVE_ENROLMENT_KEY`. Make sure the system is approved and connected to your loc
I've changed "standard Enclave policy" to "Direct Access Policy".

What needs to happen to the ports?

2023-01-26 13:22 UTC, enclave-tom commented on docs/kb/guacamole.md
> +2. In your web browser, navigate to `[YourVirtualNetworkAddress]:8080/guacamole`. You should be redirected to the Guacamole login page. If you've registered a DNS name for the server, you can also us
doesn't seem to be an option with the container, you can change the port exposed but that won't take affect under enclave

2023-01-26 13:23 UTC, enclave-alistair commented on docs/kb/guacamole.md
> +7. Navigate to `portal.enclave.io` in your browser and identify the Guacamole server; it should have enrolled using `ENCLAVE_ENROLMENT_KEY`. Make sure the system is approved and connected to your loc
They should specify ACLs in the policy to only allow access to the guacamole port. https://docs.enclave.io/management/policy/#access-control-rules

2023-01-26 13:26 UTC, enclave-alistair commented on docs/kb/guacamole.md
> +2. In your web browser, navigate to `[YourVirtualNetworkAddress]:8080/guacamole`. You should be redirected to the Guacamole login page. If you've registered a DNS name for the server, you can also us
Fair enough.

2023-01-26 13:29 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +7. Navigate to `portal.enclave.io` in your browser and identify the Guacamole server; it should have enrolled using `ENCLAVE_ENROLMENT_KEY`. Make sure the system is approved and connected to your loc
👍

2023-01-26 13:54 UTC, enclave-alistair commented on docs/kb/guacamole.md
> +7. Navigate to `portal.enclave.io` in your browser and identify the Guacamole server; it should have enrolled using `ENCLAVE_ENROLMENT_KEY`. Make sure the system is approved and connected to your loc
Is that the correct link?

2023-01-26 15:04 UTC, enclave-charlie commented on docs/kb/guacamole.md
> +7. Navigate to `portal.enclave.io` in your browser and identify the Guacamole server; it should have enrolled using `ENCLAVE_ENROLMENT_KEY`. Make sure the system is approved and connected to your loc
Fixed

2023-01-26 18:18 UTC, enclave-alistair approved these changes

2023-01-26 18:18 UTC, merged