Add auto update to linux setup
enclave-networks/docs pull request #58
Opened 2023-03-06 10:39 UTC by enclave-tom

2023-03-06 11:07 UTC, enclave-alistair requested changes
Nice; just some wording adjustments now its moved, and one question about cron.

2023-03-09 14:22 UTC, enclave-tom commented on docs/setup/linux.md
> +    4. Schedule a cronjob to regularly check for and install upgrades
moved this to dpkg-reconfigure

2023-03-28 10:59 UTC, enclave-alistair requested changes
Minor heading correction.

2023-03-28 10:59 UTC, enclave-alistair commented on docs/setup/linux.md
> +# Automatic Updates
You should use the double `##` here to indicate a sub-heading, otherwise it'll be considered a top-level item. You should also have a blank line before the blurb text.

Also, should this section follow the "Updating Enclave" section rather than the "Uninstalling" one?

2023-03-30 14:35 UTC, merged