first pass of tags page
enclave-networks/docs pull request #6
Opened 2021-04-13 14:41 UTC by enclave-marc-barry

2021-04-14 11:35 UTC, enclave-alistair commented on docs/management/tags.md
> +> **Managed vs. unmanaged systems:** When one or more Tags are attached to a system, that system automatically switches into Managed mode. This means all connectivity for that system must be defined
Suggest "will no longer accept commands from local user(s)" should be clarified to indicate it cannot be modified/configured locally. Users can still give some commands to enclave (stop/start/status, etc).

2021-04-16 14:42 UTC, enclave-alistair requested changes
Looks pretty good, a couple of minor adjustments.

2021-04-16 14:42 UTC, enclave-alistair commented on docs/management/tags.md
> +Once defined, account Administrators can add member systems to Tags and composed them policies to create connectivity.
```suggestion
Once defined, account Administrators can add member systems to Tags and compose Policies to create connectivity.
```

2021-04-16 17:07 UTC, enclave-marc-barry commented
changes made, merging

2021-04-16 17:07 UTC, merged