Docs Updates
enclave-networks/docs pull request #61
Opened 2023-03-20 10:07 UTC by enclave-tom

closes #25 
closes #52

2023-03-20 14:36 UTC, enclave-charlie requested changes

2023-03-20 14:36 UTC, enclave-charlie commented on docs/support/troubleshooting.md
> +In order to help with troubleshooting support may request logs from you this will often come with a `loglevel`. This increases the verbosity of the logs stored by Enclave.
Doesn't feel very clear. Might be worth explaining in more detail what log levels do, and the purpose of the steps below. e.g.

"In order to help with troubleshooting,  our support team may ask you to provide logs. The amount of information recorded in a log is determined the by "Log Level", which we may ask you to increase. The following steps outline how to submit logs at a given log level: "

2023-03-20 14:36 UTC, enclave-charlie commented on docs/support/troubleshooting.md
> +    !!! note
Can probably simplify the message. How does the user know which files (and how many) they need to send?

2023-03-29 16:44 UTC, enclave-marc-barry commented on docs/support/troubleshooting.md
> +2. Select `settings` and enable debug logging. From here use the app as you would normally to reproduce the bug.
Sounds like Enclave needs to be running / started before step 2 will work?

2023-04-14 14:15 UTC, enclave-charlie requested changes
Looking good, but I'd add a couple more commas to break up the text (I've highlighted them in the review comments)

2023-04-14 14:15 UTC, enclave-charlie commented on docs/support/troubleshooting.md
> +2. Now we will set the profile log level to ensure it is retained after a restart of the process. This is done to ensure we continue to get the correct log information between restarts. This is usefu
I'd add a couple more commas here (around "for example" and after "to do this"):

"This is done to ensure we continue to get the correct log information between restarts. This is useful if, for example, the issue only happens when starting Enclave or we need to restart Enclave a few times for the issue to manifest. To do this, perform the following steps:"

2023-04-14 14:15 UTC, enclave-charlie commented on docs/support/troubleshooting.md
> +    - **Linux/Mac**: Run this command in your terminal `sudo enclave set-config loglevel <desired-log-level>`
Feels like there should be a semi-colon introducing the command:

"Run this command in your terminal: `sudo enclave set-config loglevel <desired-log-level>`"

2023-04-14 14:15 UTC, enclave-charlie commented on docs/support/troubleshooting.md
> +On mobile the process is slightly different.
A colon might be more appropriate than a full-stop, as the sentence introduces text:

"On mobile the process is slightly different: "

2023-04-14 14:15 UTC, enclave-charlie commented on docs/support/troubleshooting.md
> +1. Open the Enclave app ensuring that enclave is first running then select the hamburger menu in the top left.
Reckon a few more commas would help here:

"Open the Enclave app, ensuring that enclave is first running, and then select the hamburger menu in the top left."

2023-04-14 14:15 UTC, enclave-charlie commented on docs/support/troubleshooting.md
> +2. Select `settings` and enable debug logging. From here use the app as you would normally to reproduce the bug.
I'd add a comma after "From here"

2023-04-17 15:01 UTC, enclave-charlie approved these changes
Sweet - looks good 👍

2023-04-19 09:00 UTC, merged