Add cards for the tutorials page, and add guide for on-prem access to AD.
enclave-networks/docs pull request #64
Opened 2023-04-17 13:31 UTC by enclave-alistair

Also added a section to the gateways docs more generally about resource requirement tips.

2023-04-18 15:05 UTC, enclave-charlie requested changes

2023-04-18 15:05 UTC, enclave-charlie commented on docs/tutorials/providing-access-to-onprem-ad.md
> +6. Configure a subnet filter on the policy to allow access only to your AD server (**10.0.0.1**) within your **10.0.0.0/24** subnet:
Personal preference, but I prefer "only allow access to", rather than "allow access only to"

2023-04-19 10:11 UTC, enclave-alistair commented on docs/tutorials/providing-access-to-onprem-ad.md
> +If you already have automatic fail-over of a Gateway VM through the use of a hypervisor automatic fail-over feature (for example, VMWare High Availability), that will be sufficient, and only a single
Adjusted turn of phrase.

2023-04-19 10:12 UTC, enclave-alistair commented on docs/tutorials/providing-access-to-onprem-ad.md
> +    Exposing the entire high-port dynamic range via Enclave on your AD server is not likely to cause any security issues, so for most use-cases you can expose that entire range over Enclave.
Reluctant to use `it` here since it's a new sentence. But will use a different term.

2023-04-19 10:13 UTC, enclave-alistair commented on docs/tutorials/providing-access-to-onprem-ad.md
> +    Exposing the entire high-port dynamic range via Enclave on your AD server is not likely to cause any security issues, so for most use-cases you can expose that entire range over Enclave.
Actually, I'm not sure the second sentence is even needed.

2023-04-19 10:18 UTC, enclave-alistair commented on docs/tutorials/providing-access-to-onprem-ad.md
> +        This is how high-availability / load-balancing is set up for gateways; specify more than one gateway on the receiver side with the same subnet(s), and the rest is automatic.
I'd only capitalise High-Availability if it's the name of a product or a section heading I think.  Will amend the text slightly, as well, but we've already instructed _how_ to configure this set up in the `5.` sentence itself, this tip is just pointing out that this is all that's needed to set up high-availability.

2023-04-19 10:38 UTC, enclave-charlie commented on docs/tutorials/providing-access-to-onprem-ad.md
> +        This is how high-availability / load-balancing is set up for gateways; specify more than one gateway on the receiver side with the same subnet(s), and the rest is automatic.
Must have been tired - you're right.

2023-04-19 10:38 UTC, enclave-charlie approved these changes

2023-04-19 10:40 UTC, merged