Added new wording for unattended installer as well as new arch
enclave-networks/docs pull request #75
Opened 2023-05-23 11:47 UTC by enclave-tom

relates to #74

2023-05-23 13:05 UTC, enclave-alistair requested changes

2023-05-23 13:05 UTC, enclave-alistair commented on docs/setup/windows.md
> +=== "32-bit executable"
We should add an equivalent block for our arm64 executable.

2023-05-23 13:05 UTC, enclave-alistair commented on docs/setup/windows.md
> +        ./enclave-setup-unattended-x32-<version>.exe -q
I think the file name is `x86`?

2023-05-23 13:05 UTC, enclave-alistair commented on docs/setup/windows.md
> +If an installion doesn't work as expected, examine the log files at `C:\Program Files\Enclave Networks\Enclave\Agent\logs`. If an install is interrupted, use the Enclave setup file to restart the pro
Typo; `installion` -> `installation`.

2023-05-23 13:05 UTC, enclave-alistair commented on docs/setup/windows.md
> +## Troublehsooting install issues
```suggestion
## Troubleshooting install issues
```

2023-05-23 13:06 UTC, enclave-alistair commented on docs/setup/windows.md
> +=== "64-bit MSI package"
I'm guessing we should probably add the x86 and arm64 MSI package links as well?

2023-05-24 09:28 UTC, enclave-tom commented on docs/setup/windows.md
> +=== "64-bit MSI package"
It's there already?

2023-05-24 09:31 UTC, enclave-alistair commented on docs/setup/windows.md
> +=== "64-bit MSI package"
I can see the exe ones but not the MSI ones?

2023-05-31 12:33 UTC, enclave-alistair approved these changes
👍

2023-05-31 12:34 UTC, merged