Changed the supported enclave versions
enclave-networks/docs pull request #99
Opened 2023-07-31 14:40 UTC by enclave-tom

I've also removed the `purge` command as currently it's use doesn't match our description this is being looked at as part of https://github.com/enclave-networks/fabric/issues/782

2023-07-31 15:49 UTC, enclave-marc-barry commented
Why have we dropped support for 14.04, Debian 9 and Fedora 32?

2023-07-31 15:59 UTC, enclave-marc-barry commented
Ok, I see - linking this back to https://github.com/enclave-networks/fabric/issues/825

2023-08-02 06:56 UTC, enclave-alistair requested changes

2023-08-02 06:56 UTC, enclave-alistair commented on docs/setup/linux.md
> -    Remove the Enclave package and any configuration files (including private any keys generated during enrolment).
Should we add a separate section after the distro tabs telling people how to delete their profiles?

2023-08-02 08:47 UTC, enclave-tom commented on docs/setup/linux.md
> -    Remove the Enclave package and any configuration files (including private any keys generated during enrolment).
can do it should be as simple as `sudo rm -rd /etc/enclave/`

2023-08-10 09:08 UTC, enclave-alistair requested changes

2023-09-11 09:54 UTC, enclave-alistair approved these changes

2023-09-11 10:01 UTC, merged